[ubuntu]
# 10.3.130.201 ansible_connection=ssh ansible_ssh_user=asane ansible_ssh_private_key_file=~/.ssh/id_rsa
#10.3.130.201 ansible_connection=ssh ansible_user=asane ansible_ssh_pass=p@sser01
192.168.76.50 ansible_connection=ssh ansible_user=root ansible_ssh_pass=p@sser01


