---
- name: Telecharger Tomcat{{ tomcat_major_version }} depuis tomcat.apache.org
  hosts: ubuntu
  vars:
    tomcat_version: "10.1.20"
    tomcat_major_version: "10"
    download_url: https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
   # ansible_become_password:'p@sser01'
  tasks:
    # - name: Telecharger Open JDK 11
    #   become: yes
    #   apt:
    #     name: openjdk-11-jre-headless
    #     update_cache: yes
    #     state: present
  
    - name: Installer Open JDK 17
      become: yes
      apt:
        name: openjdk-17-jre-headless
        update_cache: yes
        state: present

    - name: Installer Open JDK 19
      become: yes
      apt:
        name: openjdk-19-jre-headless
        update_cache: yes
        state: present

    - name: Installer Open JDK 21
      become: yes
      apt:
        name: openjdk-21-jre-headless
        update_cache: yes
        state: present
  
    - name: valider si java est disponible
      shell: 
        java -version
     
    - name: Creer un group
      become: yes
      group: 
        name: tomcat
        state: present

    - name: Creer un user
      become: yes
      user:
        name: tomcat
        state: present

    - name: Creer un un repertoire /opt/tomcat{{ tomcat_major_version }}
      become: yes
      file:
        path: /opt/tomcat{{ tomcat_major_version }}
        state: directory
        mode: 0755
        owner: tomcat
        group: tomcat

    - name: Telecharger Tomcat en utilisant unarchive
      become: yes
      unarchive:
        src: "{{download_url}}"
        dest: /opt/tomcat{{ tomcat_major_version }}
        mode: 0755
        remote_src: yes
        group: tomcat
        owner: tomcat
    
    - name: Deplacer les fichiers dans le repertoire /opt/tomcat{{ tomcat_major_version }} 
      become: yes
      become_user: tomcat
      shell: "mv /opt/tomcat{{ tomcat_major_version }}/apache*/* /opt/tomcat{{ tomcat_major_version }}"

    - name: Creer un service
      become: yes
      copy: 
        content: |-
          [Unit]
          Description=Tomcat Service
          Requires=network.target
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-1.17.0-openjdk-amd64"
          Environment="CATALINA_PID=/opt/tomcat{{ tomcat_major_version }}/logs/tomcat.pid"
          Environment="CATALINA_BASE=/opt/tomcat{{ tomcat_major_version }}"
          Environment="CATALINA_HOME=/opt/tomcat{{ tomcat_major_version }}"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

          ExecStart=/opt/tomcat{{ tomcat_major_version }}/bin/startup.sh
          ExecStop=/opt/tomcat{{ tomcat_major_version }}/bin/shutdown.sh
          Restart=on-abnormal

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service

    - name: Reload le SystemD pour appliquer les configurations
      become: yes
      systemd:
        daemon-reload: yes

    - name: Enable tomcat service and start
      become: yes
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Connection au serveur Tomcat sur le port 8080 and check status 200 - Try 5 times
      tags: test
      uri:
        url: http://localhost:8080
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 10
